# Generated by Django 2.1.5 on 2020-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('emp_num', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
