# Generated by Django 2.1.5 on 2020-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_auto_20200705_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_num',
            field=models.IntegerField(null=True),
        ),
    ]
